# Generated by Django 5.0 on 2025-02-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Informações da Empresa',
                'verbose_name_plural': 'Informações da Empresa',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('start_date', models.DateField(verbose_name='Data Inicial')),
                ('end_date', models.DateField(verbose_name='Data Final')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
            options={
                'verbose_name': 'Ano Fiscal',
                'verbose_name_plural': 'Anos Fiscais',
                'ordering': ['-year'],
            },
        ),
    ]
