# Generated by Django 5.0.2 on 2025-03-10 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('account_count', models.IntegerField(default=0, verbose_name='Qtd. Contas')),
                ('company_count', models.IntegerField(default=0, verbose_name='Qtd. Empresas')),
                ('fiscal_year_count', models.IntegerField(default=0, verbose_name='Qtd. Anos Fiscais')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='Qtd. Lançamentos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
