# Generated by Django 5.0.2 on 2025-02-27 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.account', verbose_name='Conta Pai'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('A', 'Ativo'), ('L', 'Passivo'), ('E', 'Patrimônio Líquido'), ('R', 'Receita'), ('X', 'Despesa')], max_length=1, verbose_name='Tipo'),
        ),
    ]
