# Generated by Django 5.0.2 on 2025-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_company_id',
            field=models.IntegerField(blank=True, help_text='ID da última empresa utilizada pelo usuário', null=True),
        ),
    ]
