# Generated by Django 5.0.2 on 2025-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_regime',
            field=models.CharField(choices=[('SN', 'Simples Nacional'), ('LR', 'Lucro Real'), ('LP', 'Lucro Presumido')], default='SN', max_length=2, verbose_name='Regime Tributário'),
        ),
    ]
