# Generated by Django 5.0.2 on 2025-03-11 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_company_id'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('entry_type', models.CharField(choices=[('sale', 'Venda'), ('purchase', 'Compra'), ('expense', 'Despesa'), ('transfer', 'Transferência'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Lançamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_templates', to='accounts.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Modelo de Lançamento',
                'verbose_name_plural': 'Modelos de Lançamentos',
                'ordering': ['name'],
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='TransactionTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor/Porcentagem')),
                ('is_percentage', models.BooleanField(default=True, help_text='Se marcado, o valor será tratado como porcentagem do valor base.', verbose_name='É porcentagem?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_credit_items', to='accounts.account', verbose_name='Conta de Crédito')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_debit_items', to='accounts.account', verbose_name='Conta de Débito')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transactiontemplate', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Item do Modelo de Lançamento',
                'verbose_name_plural': 'Itens do Modelo de Lançamento',
                'ordering': ['order', 'id'],
            },
        ),
    ]
