# Generated by Django 5.0.2 on 2025-03-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactiontemplate_transactiontemplateitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontemplateitem',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor/Porcentagem'),
        ),
    ]
