# Generated by Django 5.0.2 on 2025-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('BS', 'Balanço Patrimonial'), ('IS', 'Demonstração do Resultado'), ('CF', 'Fluxo de Caixa'), ('TB', 'Balancete'), ('GL', 'Razão Geral')], max_length=2, verbose_name='Tipo'),
        ),
    ]
